# Continuous Integration Workflow for Military Logistics Management Application
name: CI Workflow

# Trigger the workflow on push and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Set up the jobs to perform
jobs:
  # Set up the environment, build the application, and run the tests.
  build:
    runs-on: ubuntu-latest

    # Set up a service container to host the postgreSQL database.
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: db_admin
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # Run a health check to make sure the database is available.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Fetch all branch references for Sonar scan.
    - name: Fetch all branches
      run: git fetch --unshallow

    # Set up the JDK for the Spring Boot Application
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Build and test the application
    - name: Build and Test
      run: ./gradlew build test

    # Run the linter
    - name: Run Checkstyle
      run: |
        ./gradlew checkStyleMain
        ./gradlew checkStyleTest

    # Run Sonar analysis tool
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonar

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/test-results/

    # Coverage was run during the build so upload the report
    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: build/reports/jacoco/html/

      # Generate the coverage badges for the README file
    - name: Generate JaCoCO Badge
      run: ./gradlew generateJacocoBadge

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit README update
      run: |
        git add README.md
        git commit -m "Update Jacoco badge in README"
      continue-on-error: true # Avoid error if there are no changes

    - name: Push changes
      permissions:
        contents: write
        pull-requests: none
        issues: none
      run: git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}