# Continuous Integration Workflow for Military Logistics Management Application
name: CI Workflow

# Trigger the workflow on push and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Set up the jobs to perform
jobs:
  # Set up the environment, build the application, and run the tests.
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Fetch all branch references for Sonar scan.
    - name: Fetch all branches
      run: git fetch --unshallow

    # Set up the JDK for the Spring Boot Application
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

      # Build and test the application
    - name: Build and Test
      run: ./gradlew build test --info
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        DB_TEST_URL: ${{ secrets.DB_TEST_URL }}
        DB_TEST_USERNAME: ${{ secrets.DB_TEST_USERNAME }}
        DB_TEST_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
        SPRING_PROFILES_ACTIVE: test

    # Run the linter
    - name: Run Checkstyle
      run: |
        ./gradlew checkStyleMain
        ./gradlew checkStyleTest

    # Run Sonar analysis tool
    - name: SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonar

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/test-results/

    # Coverage was run during the build so upload the report
    - name: Upload JaCoCo Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: build/reports/jacoco/html/